-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" "Role" DEFAULT E'USER',

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Recipe" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "ingredients" TEXT[],
    "directions" TEXT[],
    "imageUrl" TEXT,
    "published" BOOLEAN DEFAULT false,
    "authorId" INTEGER,

    PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User.username_unique" ON "User"("username");

-- AddForeignKey
ALTER TABLE "Recipe" ADD FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddInitialData
INSERT INTO "User" (username, password) VALUES
('admin','$2b$10$srrc4FtL31OR1hc0mBCmj.EapyKiVS7m9hpjnFqsDvtwnJ7HrdynS'),
('user1','$2b$10$pC4L/7kSsVtoU6eEW1oKNO/sPAjuHC6tYJzLuyt6k4bdyxmJ0AuWu'),
('user2','$2b$10$rCUatdcpDLAY6Q.8UodbJOFtg2t7iYa.UEBnDj6ozcyz2xwdIg6gG');

INSERT INTO "Recipe" (title, ingredients, directions, "imageUrl", "authorId") VALUES
('Corn Fritters II',ARRAY['2 eggs, separated','1 tablespoon salt','pepper','2 tablespoon flour','2 cup grated fresh corn'],ARRAY['Beat the egg yolks and add the flour, salt and a little pepper.','Add the corn and fold in the stiffly beaten egg whites.','Drop small spoonfuls on greased griddle or frying pan.','Do not cook too fast.','.'],'https://publicdomainrecipes.org/recipes/corn-fritters-ii/Corn%20Fritters%20II_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',1),
('Peach Fritters',ARRAY['1/2 cup sugar','1 cup milk','2 eggs, well beaten','1/2 teaspoon lemon juice','1 /3 cup butter','1/2 teaspoon vanilla','2 cup flour','1 1/2 cup chopped peaches, fresh or canned','3 teaspoon baking powder','1/2 teaspoon salt','whipped cream'],ARRAY['Cream the butter and sugar, add the eggs and beat thoroughly.','Sift dry ingredients together and add the milk slowly.','Fold in peaches, lemon juice and vanilla.','Drop by teaspoonfuls into hot fat.','Fry golden brown.','Serve with whipped cream or sprinkle with powdered sugar.','.'],'https://publicdomainrecipes.org/recipes/peach-fritters/Peach%20Fritters_hu2ffbc062d4fb41aba1a16dea5ff99300_65104_350x350_fill_q75_box_smart1.jpg',2),
('Sour Cherry Fritters',ARRAY['1 cup flour, sifted','2 tablespoon sugar','1 teaspoon baking powder','2 eggs, separated','1/2 teaspoon salt','3 tablespoon water','1 cup pitted sour cherries'],ARRAY['Sift together the flour, baking powder, salt and sugar.','Combine the beaten egg yolks with water and mix until smooth.','Fold in the stiffly-beaten egg whites and add the cherries.','Drop by spoonfuls into hot fat (360f) and cook 2 to 5 minutes or until browned.','Drain on absorbent paper and serve with powdered sugar or fruit sauce.','Other fruits or berries may be used.','.'],'https://publicdomainrecipes.org/recipes/sour-cherry-fritters/Sour%20Cherry%20Fritters_hu24d0e896f04700494cb82bc909d8fa69_97533_350x350_fill_q75_box_smart1.jpg',3),
('Apple Ring Fritters',ARRAY['1 cup sifted flour','3/4 cup milk','1 1/2 teaspoon baking powder','1 egg','2 tablespoon sugar','4 large apples','1/2 teaspoon salt'],ARRAY['Sift dry ingredients.','Add milk and egg.','Beat well.','Peel and core apples and slice in rings about 1/4 inch thick.','Dip rings in batter and drop into skillet containing 1/2 inch of hot melted shortening.','Fry until golden brown on both sides.','Drain on paper towel.','Mix sugar and cinnamon together and sprinkle over fritters.','.'],'https://publicdomainrecipes.org/recipes/apple-ring-fritters/Apple%20Ring%20Fritters_hu5c770bb5f7c0787f07f69ba8fbb0308d_125244_350x350_fill_q75_box_smart1.jpg',1),
('Potato Pancakes',ARRAY['2 eggs, separated','1/2 cup flour','1 cup mashed potatoes','1 cup milk','2 teaspoon baking powder'],ARRAY['Add egg yolks to the mashed potatoes and mix well.','Add the flour and baking powder alternate with the milk until smooth.','Fold in the stiffly beaten egg whites and drop spoonfuls on hot greased griddle or skillet.','Finely chopped onion is sometimes sprinkled on the batter on griddle before turning.','Serve hot with meat.','.'],'https://publicdomainrecipes.org/recipes/potato-pancakes/Potato%20Pancakes_huf8a14e49b0f493a9dd59597d5c99511f_101261_350x350_fill_q75_box_smart1.jpg',2),
('Fried Corn Meal Mush',ARRAY['1 cup corn meal','1 teaspoon salt','2 quart boiling water'],ARRAY['Moisten corn meal with a little cold water and stir into the salted boiling water.','Cook over slow fire, stirring often, for 45 minutes.','(Most of the corn meal sold today has been processed to cook much faster, so follow the directions.',') Pour the hot corn meal into a greased loaf pan or glass baking dish.','Let stand, uncovered, until cold and firm.','Cut into slices dip in flour and fry in hot fat until browned.','Serve with syrup.','Wonderful with sausage.','.'],'https://publicdomainrecipes.org/recipes/fried-corn-meal-mush/Fried%20Corn%20Meal%20Mush_hueeb37d6e52cd4f59017090bf1c3f032a_95768_350x350_fill_q75_box_smart1.jpg',3),
('Corn Meal Griddle Cakes',ARRAY['2 cup corn meal','2 eggs','1/2 cup flour','2 cup buttermilk','1 teaspoon baking powder','2 tablespoon butter','1 teaspoon soda','1 1/2 teaspoon salt'],ARRAY['Sift flour, corn meal, baking powder, soda and salt.','Sift again.','Beat eggs well, add the buttermilk and combine with the dry ingredients.','Beat until smooth and add melted butter.','Bake on hot griddle.','The &#39;dutch&#39; housewife rubbed the griddle with the flat part of a raw turnip cut in half, to prevent sticking.','Some used a little cloth bag filled with salt.','Serve with brown sugar or syrup.','.'],'https://publicdomainrecipes.org/recipes/corn-meal-griddle-cakes/Corn%20Meal%20Griddle%20Cakes_hubf901b198f408462a868d6ff8fdb9a26_56983_350x350_fill_q75_box_smart1.jpg',1),
('German Egg Pancakes',ARRAY['5 eggs, separated','1 cup flour, sifted','1/2 cup milk'],ARRAY['Put the yolks of 5 eggs in a bowl and beat until very light.','Add the milk and flour gradually and mix into a smooth batter which is not too thick.','Fold in the stiffly beaten egg whites.','Drop large spoonfuls on a hot greased griddle.','Serve hot sprinkled with sugar or spread with currant or other tart jelly .'],'https://publicdomainrecipes.org/recipes/german-egg-pancakes/German%20Egg%20Pancakes_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',2),
('Old-Fashioned Flannel Cakes',ARRAY['2 cup flour','2 cup milk','1 tablespoon baking powder','2 eggs, separated','1 teaspoon salt','2 tablespoon melted butter'],ARRAY['Sift together in a bowl the flour, salt and baking powder.','Beat the egg yolks and add the milk.','Pour milk mixture slowly into the dry ingredients and beat to a smooth batter.','Add the melted butter then fold in the stiffly beaten egg whites.','Bake on hot griddle.','.'],'https://publicdomainrecipes.org/recipes/old-fashioned-flannel-cakes/Old-Fashioned%20Flannel%20Cakes_huef7eb02f079f7dbe1269c47637faea84_40515_350x350_fill_q75_box_smart1.jpg',3),
('Deviled Eggs II',ARRAY['6 hard-boiled eggs','2 teaspoon soft butter','1/2 teaspoon prepared mustard','salt','pepper','paprika'],ARRAY['Remove shells and cut eggs in half.','Mash the yolks to a smooth paste, adding the mustard, butter, salt and pepper.','When well mixed press into the cup- shaped egg whites, round the tops and sprinkle with paprika.','For a special treat, add 2 tablespoon finely chopped ham or a small can of deviled ham to the egg yolk mixture.'],'https://publicdomainrecipes.org/recipes/deviled-eggs-ii/Deviled%20Eggs%20II_hu793c5844f9e55458cf347f6204e6189c_81496_350x350_fill_q75_box_smart1.jpg',1),
('Fruit Salad Dressing',ARRAY['1/2 cup sugar','1/2 cup pineapple juice','1 1/2 tablespoon flour','1/2 cup lemon juice','2 eggs','1 cup whipped cream'],ARRAY['Combine the fruit juices and stir slowly into the flour and sugar.','Cook.','Stirring constantly, until it thickens, (or cook in double boiler).','Add the beaten eggs and cook for another minute.','Let cool and fold in the whipped cream.','.'],'https://publicdomainrecipes.org/recipes/fruit-salad-dressing/Fruit%20Salad%20Dressing_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',2),
('Beet And Apple Salad',ARRAY['2 cup apples, diced','2 hard boiled eggs','2 cup cooked beets, diced','1/2 cup salad dressing','1/4 cup chopped nuts','parsley'],ARRAY['Mix the apples, beets, and chopped eggs.','Add salad dressing (see grandma&#39;s salad dressing).','Mix and garnish with chopped nuts and parsley.','.'],'https://publicdomainrecipes.org/recipes/beet-and-apple-salad/Beet%20And%20Apple%20Salad_hud816acecbcd08b49617253d644b5db8a_124203_350x350_fill_q75_box_smart1.jpg',3),
('Cucumber Salad',ARRAY['2 medium cucumbers','2 tablespoon vinegar','1 medium onion','sour cream','salt','pepper'],ARRAY['Pare and thinly slice cucumber and onion sprinkle with a teaspoon of salt and let stand for a few minutes.','Pat with towel or absorbent paper to take out all moisture possible.','Place cucumbers and onions in serving dish, add the vinegar and mix.','Pour on enough sour cream to half cover and dust with pepper.','Chill.','.'],'https://publicdomainrecipes.org/recipes/cucumber-salad/Cucumber%20Salad_hue631eddd1ae3e39cc92eb0ff0cb18fc8_85503_350x350_fill_q75_box_smart1.jpg',1),
('Bean Salad II',ARRAY['3 cup navy beans, baked or boiled','3 hard boiled eggs','2 tablespoon vinegar','1 medium onion','2/3 cup boiled salad dressing','2 tablespoon pickle relish, or 1-large pickle','1 1/2 teaspoon salt'],ARRAY['Chop the onion fine, the boiled eggs, add the relish, or the pickle, chopped and the beans.','Mix well together and add salt and salad dressing.','Chill and serve.','Green string beans, cut in 1-inch pieces may be used for this salad.','.'],'https://publicdomainrecipes.org/recipes/bean-salad-ii/Bean%20Salad%20II_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',2),
('Dandelion Salad',ARRAY['young dandelion, greens','1 teaspoon salt','4 thick slices bacon','1 tablespoon sugar','1/2 cup cream','4 tablespoon vinegar','2 tablespoon butter','1/2 teaspoon paprika','2 eggs','black pepper'],ARRAY['Wash dandelions and pick over carefully.','Roll in cloth and pat dry.','Put into a salad bowl and set in warm place.','Cut bacon in small cubes, fry quickly and pour over dandelions.','Put butter and cream into a skillet and melt over low heat.','Beat eggs, add salt, pepper, sugar and vinegar, then mix with the slightly warm cream mixture.','Cook over high heat until dressing is quite thick.','Pour, very hot, over the dandelions, stir well and serve.','.'],'https://publicdomainrecipes.org/recipes/dandelion-salad/Dandelion%20Salad_hu269ea0e6023e86c0ac1323ae8fc8e929_102874_350x350_fill_q75_box_smart1.jpg',3),
('Hot Slaw',ARRAY['1/2 teaspoon mustard','1 beaten egg','1 1/2 teaspoon salt','1 cup milk','1 1/2 teaspoon sugar','4 tablespoon vinegar','1 1/2 tablespoon flour','1 1/2 tablespoon butter','1/8 teaspoon pepper'],ARRAY['Shred cabbage finely.','Boil in slightly salted water until tender.','Drain.','Serve hot thoroughly mixed with warm cooked salad dressing made as follows.','Mix mustard, salt, sugar, flour, paprika and pepper.','Add egg and mix thoroughly.','Add milk and vinegar.','Cook over hot water, stirring frequently until thick.','Add butter.','Cook and stir until melted.'],'https://publicdomainrecipes.org/recipes/hot-slaw/Hot%20Slaw_hu2204eef4aeb5ab7de5f63b9adda09489_99851_350x350_fill_q75_box_smart1.jpg',1),
('Pepper Cabbage',ARRAY['2 cup shredded cabbage','1/2 cup hot salad dressing','1 large green pepper','1 teaspoon salt','1 tablespoon butter','salt','pepper','1 teaspoon flour','1 egg yolk','1/2 teaspoon dry mustard','1/2 cup vinegar'],ARRAY['Mix the cabbage, pepper, chopped fine and salt.','Let stand 1 hour in cool place.','Drain off all liquid.','Make a hot dressing with rest of ingredients.','Melt the butter and blend in the flour.','Add vinegar and stir until mixture thickens.','Mix mustard, salt and pepper and add to the liquid.','Cool for 4 minutes, pour over the beaten egg yolk and mix well.','Cook for 1 minute more.','Pour this over the pepper cabbage and mix well.'],'https://publicdomainrecipes.org/recipes/pepper-cabbage/Pepper%20Cabbage_hu700320e4c61e05c06b03ec5011d446c4_71438_350x350_fill_q75_box_smart1.jpg',2),
('Hot Dutch Potato Salad',ARRAY['4 slices bacon','1/8 teaspoon pepper','1/2 cup chopped onion','1 teaspoon sugar','1/2 cup chopped green pepper','1/4 cup vinegar','1 quart hot cubed, cooked potatoes','1 teaspoon salt','3 hard boiled eggs','1/4 cup grated raw carrot'],ARRAY['Dice bacon and pan fry.','Add chopped onion and green pepper.','Cook 3 minutes.','Add vinegar, salt, pepper, sugar and beaten egg.','Cook slightly.','Add cubed potatoes, grated carrot and diced hard-cooked eggs.','Blend and serve hot.','.'],'https://publicdomainrecipes.org/recipes/hot-dutch-potato-salad/Hot%20Dutch%20Potato%20Salad_hu8fca8eb03028ad06a02677768c9cbaf1_80426_350x350_fill_q75_box_smart1.jpg',3),
('Grandma&#39;s Salad Dressing',ARRAY['1 cup sugar','1 cup water','4 - 5 eggs','1 cup vinegar','2 tablespoon flour','salt','pepper','1 tablespoon mustard'],ARRAY['Mix dry ingredients thoroughly.','Beat eggs and add all dry ingredients, then mix with heated water and vinegar.','Cook in double boiler until thick.','Fine for potato or egg salad or on fresh tomatoes.','.'],'https://publicdomainrecipes.org/recipes/grandmas-salad-dressing/Grandma%27s%20Salad%20Dressing_hu76078218626206ddfe860fcb3f0efb7d_77961_350x350_fill_q75_box_smart1.jpg',1),
('A Good Pennsylvania Dutch Salad Dressing',ARRAY['2 hard boiled eggs, mashed','1 tablespoon vinegar','a little grated onion','1/2 teaspoon salt','3 tablespoon salad oil','pinch of pepper'],ARRAY['Mix well together, then put on lettuce and turn and stir until it is well covered with the dressing.','Good with any green salad.','.'],'https://publicdomainrecipes.org/recipes/a-good-pennsylvania-dutch-salad-dressing/A%20Good%20Pennsylvania%20Dutch%20Salad%20Dressing_hua50c1b0a56710118b5adcab48617484b_38094_350x350_fill_q75_box_smart1.jpg',2),
('Pennsylvania Cole Slaw',ARRAY['1 head young cabbage','1/2 cup sugar','1/2 cup cream','1/2 cup vinegar','1 teaspoon salt'],ARRAY['Beat cream, sugar, vinegar and salt together thoroughly until the dressing is like whipped cream.','Discard outer leaves of cabbage.','Shred the rest finely and combine with dressing just before it is ready to serve.','As variation: add shredded green and red peppers.','.'],'https://publicdomainrecipes.org/recipes/pennsylvania-cole-slaw/Pennsylvania%20Cole%20Slaw_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',3),
('Sweet Potato Croquettes',ARRAY['1 pint mashed sweet potatoes','1 tablespoon sugar','1 tablespoon butter','1 egg white','1 teaspoon salt','bread crumbs'],ARRAY['Mash sweet potatoes very fine and add salt, sugar and melted butter.','Shape into croquette rolls or patties and chill in the refrigerator for a half hour.','Then roll in bread crumbs, dip in the egg white, slightly beaten, and in the crumbs again.','Bake in a shallow, greased baking dish for 20 minutes, in hot oven (400f).','For a modern variation of this old recipe, place a marshmallow in the center of each with the potato mixture coating it completely.','.'],'https://publicdomainrecipes.org/recipes/sweet-potato-croquettes/Sweet%20Potato%20Croquettes_hu83efef23015ccddaa084670939f6a2a6_88416_350x350_fill_q75_box_smart1.jpg',1),
('Schnitzel Beans',ARRAY['4 slices bacon','1 teaspoon salt','1 quart string beans','1/4 teaspoon pepper','3 medium onions, sliced','1 cup hot water','2 cup tomatoes, chopped'],ARRAY['Dice the bacon and fry until crisp.','Slice the onions and fry until soft.','Cut the beans into small (1-inch) pieces and brown them slightly with the bacon and onions.','Add the tomatoes, seasoning and boiling water.','Cover and cook very slowly until beans are tender.','Add water if necessary, so there will be a little sauce to serve with the beans.'],'https://publicdomainrecipes.org/recipes/schnitzel-beans/Schnitzel%20Beans_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',2),
('Scalloped Spinach',ARRAY['2 pound spinach','2 eggs, beaten','2 cup milk','2 cup bread crumbs','4 tablespoon butter','1/2 cup chopped bacon','salt','pepper'],ARRAY['Wash spinach thoroughly.','Drain and cook with a little water in covered pot, over moderate heat for 8 to 10 minutes.','Drain and chop the spinach.','Add milk, the beaten eggs, 1 1/2 cups of the bread crumbs, melted butter, salt and pepper then mix well.','Sprinkle the remaining 1/2 cup bread crumbs and the chopped bacon, on the top.','Bake in moderate oven (350f) for 35 minutes.','.'],'https://publicdomainrecipes.org/recipes/scalloped-spinach/Scalloped%20Spinach_hu2c3bfb67ac7ee85c8e9300b97c428a0b_49605_350x350_fill_q75_box_smart1.jpg',3),
('Fried Egg Plant',ARRAY['4 tomatoes','flour','3 tablespoon hot fat and butter','1/2 cup milk','2 tablespoon brown sugar','salt','pepper'],ARRAY['Pare eggplant and cut in slices 1/2 inch thick.','Soak slices in salt water for about an hour.','Drain and wipe dry.','Dip slices in beaten egg and roll in fine bread or cracker crumbs.','Fry in hot fat (or deep fat) until well browned on both sides.','Serve with catsup or tomato sauce.'],'https://publicdomainrecipes.org/recipes/fried-egg-plant/Fried%20Egg%20Plant_hu61ece2863cdcc5ae1af0c1cc7950b579_55614_350x350_fill_q75_box_smart1.jpg',1),
('Fried Tomatoes II',ARRAY['4 tomatoes','flour','3 tablespoon hot fat and butter','1/2 cup milk','2 tablespoon brown sugar','salt','pepper'],ARRAY['Cut large, solid, ripe tomatoes in 1/2 inch slices.','Dredge thickly with flour.','Fry quickly in 2 tablespoons of hot drippings or butter, browning well on both sides.','Remove to serving platter, sprinkle with salt, pepper and brown sugar.','Keep warm.','Add 1 tablespoon of butter to the pan fryings and blend in a tablespoon of flour,.','Add the milk and cook, stirring constantly.','It should be about the consistency of thick cream.','Pour it over the tomatoes and serve.','.'],'https://publicdomainrecipes.org/recipes/fried-tomatoes-ii/Fried%20Tomatoes%20II_hub9ab18677c560ad337cdc26901b339b9_8336_350x350_fill_box_smart1_2.png',2),
('Sweet And Sour Beets',ARRAY['3 cup beets, diced','1/4 cup vinegar','1 cup beet water','2 teaspoon butter','1 tablespoon sugar','1 tablespoon corn, starch'],ARRAY['Cut off beet tops leaving 2 inches of the stems.','Clean well, place in pot and cover with boiling water.','Cook until tender, slip off the outer skins and dice.','Strain and save 1 cup of the water in which beets were cooked.','Add sugar, vinegar and butter.','Thicken with 1 tablespoon of corn starch and cook to the consistency of cream.','Add the diced beets, salt and pepper and heat.','.'],'https://publicdomainrecipes.org/recipes/sweet-and-sour-beets/Sweet%20And%20Sour%20Beets_hu3f788781095591141b6cd21411c75ceb_71023_350x350_fill_q75_box_smart1.jpg',3),
('Scalloped Tomatoes III',ARRAY['1 small onion, sliced','3 cup tomatoes, canned or fresh','1/2 cup bread crumbs, buttered','1 medium cucumber, pared and sliced','1/2 cup grated cheese','pepper','salt'],ARRAY['Into a greased baking dish or casserole place a layer of tomatoes, add half the cucumber and onion slices and half of the crumbs.','Repeat with more tomatoes and remaining cucumbers, onions and crumbs.','Top with tomatoes and sprinkle with cheese.','Bake in moderate oven, (375f) 40 minutes.','.'],'https://publicdomainrecipes.org/recipes/scalloped-tomatoes-iii/Scalloped%20Tomatoes%20III_hu26c55f665cd0e5c3d0eaecd82a1a149a_55699_350x350_fill_q75_box_smart1.jpg',1),
('Scalloped Potatoes II',ARRAY['6 potatoes, sliced','3 tablespoon butter','1 onion, chopped','2 tablespoon flour','2 cup hot milk','pepper','3/4 cup grated cheese'],ARRAY['Melt butter in double boiler or sauce pan.','Add flour, seasoning and stir smooth.','Slowly add the hot milk stirring constantly.','When it thickens melt the grated cheese in the sauce.','Into a buttered baking dish or casserole put layers of the sliced potatoes, onions and cheese sauce, repeating until all ingredients are used.','Bake in a moderate oven (350f) for 1 hour.','.'],'https://publicdomainrecipes.org/recipes/scalloped-potatoes-ii/Scalloped%20Potatoes%20II_hu93204b9d1f96c10cd2ec3fe75a3e9753_44802_350x350_fill_q75_box_smart1.jpg',2),
('Dutch Potato Croquettes',ARRAY['1 1/2 cup cold mashed potatoes','1/4 teaspoon salt','1 tablespoon butter','1/2 teaspoon minced onion','1 teaspoon minced parsley','dash of pepper','2 tablespoon cream','1 egg','corn meal'],ARRAY['Mix up a paste with the potatoes and butter, add the parsley, salt and pepper, cream, onion and egg.','Mold into croquettes, dip into the egg white, roll in corn meal.','Fry in deep fat .'],'https://publicdomainrecipes.org/recipes/dutch-potato-croquettes/Dutch%20Potato%20Croquettes_hudd41b55afbdd815fddb04655a01c71d5_52135_350x350_fill_q75_box_smart1.jpg',3),
('Hashed Brown Potatoes',ARRAY['6 medium cold boiled potatoes','3 raw green peppers','1/4 teaspoon celery salt','shortening','salt','pepper'],ARRAY['Chop potatoes fine, season with celery salt, salt and pepper to taste.','Remove seeds and stem from pepper, wash drain and chop fine.','Mix with potatoes.','Put about 1 tablespoon of melted shortening in pan and when hot, add potatoes and cook slowly.','When partly brown, fold into omelet shape in one side of pan.','Fry until a rich brown.','.'],'https://publicdomainrecipes.org/recipes/hashed-brown-potatoes/Hashed%20Brown%20Potatoes_hubddd8f93ce651e05fb9e8cfbaef38ef4_66087_350x350_fill_q75_box_smart1.jpg',1),
('Scalloped Sweet Potatoes And Apples',ARRAY['6 medium-sized sweet potatoes','4 tablespoon butter','1/2 teaspoon salt','1/2 cup brown sugar','1 teaspoon mace','1 1/2 cup sliced apples'],ARRAY['Boil sweet potatoes until tender.','Slice in 1/4 inch pieces.','Butter baking dish and put a layer of sweet potatoes in bottom, then a layer of apples.','Sprinkle with sugar, salt and mace, and dot with butter.','Repeat until dish is filled, having the top layer of apples.','Bake in moderate oven (350f) for 50 minutes.','.'],'https://publicdomainrecipes.org/recipes/scalloped-sweet-potatoes-and-apples/Scalloped%20Sweet%20Potatoes%20And%20Apples_hu7fc461a82d3213351f2a5acb1359891b_65779_350x350_fill_q75_box_smart1.jpg',2),
('Fresh Peas And New Potatoes',ARRAY['3 cup peas','1 1/2 cup milk','12 small new potatoes','1 1/2 teaspoon flour','1 1/2 teaspoon salt'],ARRAY['Cook potatoes and peas in separate pans, in salted water until soft and almost free of water.','Mix the peas and potatoes and add the milk.','Bring to the boiling point then add the butter and flour which have been blended smooth and cook until thickened.','.'],'https://publicdomainrecipes.org/recipes/fresh-peas-and-new-potatoes/Fresh%20Peas%20And%20New%20Potatoes_hu6417d162a191fe0df25be276e2a9f4cd_63887_350x350_fill_q75_box_smart1.jpg',3),
('Parsnip Patties',ARRAY['6 - 7 parsnips','1 teaspoon sugar','1 tablespoon butter or shortening','1/2 teaspoon salt','little pepper','2 eggs','milk','1/2 cup bread crumbs, dry'],ARRAY['Boil parsnips in salted water.','When soft, peel and remove the core then mash.','Add shortening, bread crumbs, salt, pepper, sugar and 1 egg and the white of the other, beaten.','Mix well and form into cakes.','Beat the remaining egg yolk with a little milk added.','Dip the cakes into the egg, roll in corn meal or bread crumbs and fry to a nice brown.','.'],'https://publicdomainrecipes.org/recipes/parsnip-patties/Parsnip%20Patties_hu8c118ccd2c5e27ddd70baa0c3c27a5ce_94781_350x350_fill_q75_box_smart1.jpg',1),
('Corn Fritters',ARRAY['1 cup corn','1 1/4 cup milk','water','1/2 teaspoon salt','1/2 teaspoon sugar','1 teaspoon baking powder','1/4 cup flour','1 egg'],ARRAY['Add milk (or part water) to corn: let stand 1/2 hour or longer, add salt, sugar, baking powder, flour, egg, well beaten, and fry to a golden brown.','.'],'https://publicdomainrecipes.org/recipes/corn-fritters/Corn%20Fritters_huf27db2f7ac11cf5ba54254cfd056e919_12016_350x350_fill_box_smart1_2.png',2);

UPDATE "User" SET role = 'ADMIN' WHERE id = 1;
